### PR TITLE
fix: description on readonly boards

### LINKED ISSUE #1635: card's description of shared boards invisible with read only permission
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. As user A, create a board `plop` and share it with user B, with read-only permission
2. As user B, sync your boards with the android app, then select the board `plop` and open a card

Description is invisible (attachments, comments and activity are visible) - the bug is reproducible for all concerned users

| mobile | desktop |
|--------|--------|
| mobile | desktop | 

### Expected behavior

Description is visible (as in the web browser app)

### Deck Android version

1.24.1

### Deck server version

1.13.0

### Nextcloud Android version

3.29.0

### Nextcloud version

29.0.1

### Device

Galaxy A5 2017 (reproduced on multiple devices)

### Android Version

11

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

_No response_

### PR DESCRIPTION
**Pull request by Ornanovitch**
- fix #1635
- closes #1641

After many attempts, I was finally able to make it! Tested with a prod server, with and without readonly boards, everything works as expected :)

| Before | After |
|--------|--------|
| desc-before | desc-after | 

But I must admit I am not fully confident with the code, I never tried to play with java code before, so I don't even understand completely why those peace of code were missing...

I'd love to have your feedbacks @stefan-niedermann

### CODE REVIEW

File: app/src/main/java/it/niedermann/nextcloud/deck/ui/card/details/CardDetailsFragment.java [hunk 1]
```diff
@@ -175,14 +175,18 @@ private void setupDescription() {
             registerEditorListener(binding.descriptionEditor);
             registerEditorListener(binding.descriptionViewer);
         } else {
+            binding.descriptionViewer.setMarkdownString(viewModel.getFullCard().getCard().getDescription());
+
             binding.descriptionEditor.setEnabled(false);
             binding.descriptionEditorWrapper.setVisibility(GONE);
-            binding.descriptionViewer.setEnabled(false);
+            binding.descriptionViewer.setEnabled(true);
```
Comment (Ornanovitch) [inline app/src/main/java/it/niedermann/nextcloud/deck/ui/card/details/CardDetailsFragment.java:182]: This change is not necessary to view the description, but it seems mandatory to interact with it (links, selection...)

File: app/src/main/res/layout/fragment_card_edit_tab_details.xml [hunk 2]
```diff
@@ -123,7 +123,7 @@
                 android:textIsSelectable="true"
                 android:textSize="@dimen/font_size_description"
                 android:translationY="1dp"
-                android:visibility="gone" />
+                android:visibility="visible" />
```
Comment (Ornanovitch) [inline app/src/main/res/layout/fragment_card_edit_tab_details.xml:126]: nothing works without this

**Comment by stefan-niedermann** [comment]
Thank you for the contribution! I'm currently on vacation and will try to review the changes after Sept 25th.

**Comment by Ornanovitch** [comment]
Hey there :)

Can I do something to move forward on this?

**Comment by Ornanovitch** [comment]
@stefan-niedermann sorry to bump you again, but I'd love to be able to use the app with read-only shared boards again, hence I kindly ask you if you're able to review and merge this soon?

**Comment by Ornanovitch** [comment]
Thanks @desperateCoder I really appreciate the feedback!

**Comment by stefan-niedermann** [comment]
Yes, I'm very sorry for the delay, you haven't been forgotten though.

**Comment by stefan-niedermann** [comment]
@Ornanovitch thank you very much for your contribution. I am very sorry for the long delay, but in the end the changes are in the `master` now and will be included in the next release (probably `1.24.2`).

**Comment by Ornanovitch** [comment]
Thanks a lot! I'm so glad :)
