### PR TITLE
Group-handling

### LINKED ISSUE #492: Filter does not seem to work as expected
**Describe the bug**
The filter functionality does not seem to work as expected. As an admin who created the board, I have granted acces to that board to a specific user group (not the individual members of that group). I have subsequently assigned specific cards to specific users **of that group**, but when I try to apply a filter I only see the admin and the group name that the users belong to as options to filter on. This problem only appears when using the Android Deck app. Using the desktop/web version the complete list of users shows up.

**To Reproduce**
1. Log in as admin to desktop/web version
2. Create a board
3. Grant acces to a specific user group
4. Create cards
5. Assign cards to specific users of the specific user group
6. Start the Android Deck app
7. Open the specific board in the app
8. Open the filter interface
9. Notice that the specific assigned users are not available as choice options

**Expected behavior**
Self-explanatory

**Screenshots**
Not available

**Smartphone (please complete the following information):**
- Device: Motorola moto g(6) play
- Android-Version: 9
- App-Store: F-Droid

### PR DESCRIPTION
**Pull request by desperateCoder**
fixes #492 #631

### CODE REVIEW

File: app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/DataBaseAdapter.java [hunk 1]
```diff
@@ -659,10 +659,10 @@ public Board getBoardByLocalIdDirectly(long localId) {
...
     }
 
-    public LiveData<List<User>> searchUserByUidOrDisplayNameForACL(final long accountId, final long notYetAssignedToACL, final String searchTerm) {
-        validateSearchTerm(searchTerm);
-        return db.getUserDao().searchUserByUidOrDisplayNameForACL(accountId, notYetAssignedToACL, "%" + searchTerm.trim() + "%");
-    }
+//    public LiveData<List<User>> searchUserByUidOrDisplayNameForACL(final long accountId, final long notYetAssignedToACL, final String searchTerm) {
+//        validateSearchTerm(searchTerm);
+//        return db.getUserDao().searchUserByUidOrDisplayNameForACL(accountId, notYetAssignedToACL, "%" + searchTerm.trim() + "%");
+//    }
```
Comment (stefan-niedermann) [inline app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/DataBaseAdapter.java:665]: If no longer needed: Why not remove?

Comment (desperateCoder) [reply app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/DataBaseAdapter.java:665]: Because for no reason. Had it there, saw it wasn't used, commenting out didn't break anything, but wasn't my focus, too. Feel free to remove

Comment (desperateCoder) [reply app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/DataBaseAdapter.java:665]: Oh, and also the method in the dao

**Comment by stefan-niedermann** [comment]
Shipped in version `1.9.7`.
